spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/gtel-micro
    username: root
    password: 123123
    hikari:
      pool-name: HikariPool
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 0
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    addresses: localhost
    port: 5672
    username: root
    password: root
    queues:
      notification:
        email: notification_email_queue
        sms: notification_sms_queue
        discord: notification_discord_queue
    exchanges:
      notification: notification_exchange
    routing-key:
      notification:
        email: notification.email.routing
        sms: notification.sms.routing
        discord: notification.discord.routing
jwt:
  prefix: Bearer
  secret: acSTK@2024
  refreshSecret: reSTK@2024
  validity: 86400

server:
  servlet:
    context-path: /user-service/api
  port: 8000
grpc:
  server:
    port: 9091